# Generated by Django 5.1.4 on 2024-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(unique=True)),
                ('data', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
