# Generated by Django 5.1.4 on 2024-12-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_form_data_alter_form_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(),
        ),
    ]
