# Generated by Django 5.1.4 on 2024-12-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
